[notifications]

[notifications.google_cloud_storage]
bucket = "cikit"
#creds will be read from `SERVICE_ACCOUNT` env variable

[notifications.github_comments]

[junit]
report_dir_pattern = "junit-report/*.xml"
