name: CI
on:
  pull_request:
jobs:
  Build:
    if: github.event.pull_request.merged == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
      - run: cargo install cargo2junit
      - run: "cargo test -- -Z unstable-options --format json > target/testreport.xml"
      - run: "cat target/testreport.xml"
