name: Publish
on:
  #push:
  workflow_dispatch:
jobs:
  Publish:
    #if: github.ref == 'refs/heads/master' || startsWith(github.ref,'refs/heads/release/')
    runs-on: ubuntu-latest
    env:
      github_run_id: ${{ github.run_id }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/checkout@v1
      - name: Install Openssl
        run: sudo apt-get install libssl-dev
      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: "x86_64-unknown-linux-musl"
      - name: Build release artefact
        uses: actions-rs/cargo@v1.0.3
        env:
          CI: "false"
          OPENSSL_LIB_DIR: /usr/lib/x86_64-linux-gnu
        with:
          command: build
          args: --target x86_64-unknown-linux-musl #--release
#      - name: Build Docker image
#        run: "docker build . -t afiore/cikit:${{ github.run_id }}"
#      - name: List Docker image
#        run: docker image ls
#      - name: Run cikit docker image
#        run: docker run afiore/cikit:${{ github.run_id }} --help
